### ISSUE TITLE
Generate x86 binary code

### ISSUE THREAD

**Issue by piranna** [pauek/ccjs#2]
I'm looking for a C/C++ compiler written in Javascript capable of generate Linux x86 .so files, something similar to LLVM.js + clangor (unluckily abandoned :-( ). My intention is to generate Node.js compiled modules from inside NodeOS. Do you think ccjs is capable of doing this, or do you know of any other alternative?

**Comment by pauek** [comment]
ccjs doesn't do this and is also abandoned at the moment. And I have no idea where to find alternatives. Sorry.
